## mportant: if the name is not exactly the same as the node name, parameters wonâ€™t be loaded, 
## and ROS2 will not display the error. In this case, your node name (which can be different 
## from the executable name)

/**:
  ros__parameters:
      communication_range : 2.0
      N_robot: 2    
      elipse_scaling_obs: 0.6 ## Elipse is computed taking into account the distance between foci scaled by this parameter - between 2 obstacles in a frontier
      elipse_scaling_robot: 0.2 ## Elipse is computed taking into account the distance between foci scaled by this parameter - between 2 drones 