## mportant: if the name is not exactly the same as the node name, parameters wonâ€™t be loaded, 
## and ROS2 will not display the error. In this case, your node name (which can be different 
## from the executable name)

/**:
  ros__parameters:
    communication_range : 2.0
    N_robot: 2
    periodic_call_time: 4
    max_no_connection_time: 10